[2025-03-22T18:46:28.286+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T18:46:28.294+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_using_python_operator.first_task manual__2025-03-22T18:46:27.319302+00:00 [queued]>
[2025-03-22T18:46:28.298+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_using_python_operator.first_task manual__2025-03-22T18:46:27.319302+00:00 [queued]>
[2025-03-22T18:46:28.298+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-22T18:46:28.304+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): first_task> on 2025-03-22 18:46:27.319302+00:00
[2025-03-22T18:46:28.309+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_using_python_operator', 'first_task', 'manual__2025-03-22T18:46:27.319302+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmps1cqglo2']
[2025-03-22T18:46:28.310+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-22T18:46:28.311+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask first_task
[2025-03-22T18:46:28.311+0000] {standard_task_runner.py:72} INFO - Started process 1215 to run task
[2025-03-22T18:46:28.336+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_using_python_operator.first_task manual__2025-03-22T18:46:27.319302+00:00 [running]> on host 4f1e28758fdd
[2025-03-22T18:46:28.381+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_using_python_operator' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T18:46:27.319302+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-22T18:46:27.319302+00:00'
[2025-03-22T18:46:28.382+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T18:46:28.390+0000] {logging_mixin.py:190} INFO - Hello World!
[2025-03-22T18:46:28.390+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-22T18:46:28.395+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T18:46:28.395+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_using_python_operator, task_id=first_task, run_id=manual__2025-03-22T18:46:27.319302+00:00, execution_date=20250322T184627, start_date=20250322T184628, end_date=20250322T184628
[2025-03-22T18:46:28.411+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-22T18:46:28.418+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-22T18:46:28.419+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
