[2025-03-22T18:16:41.119+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T18:16:41.126+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2025-03-22T18:16:40.217783+00:00 [queued]>
[2025-03-22T18:16:41.130+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2025-03-22T18:16:40.217783+00:00 [queued]>
[2025-03-22T18:16:41.130+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-22T18:16:41.135+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-03-22 18:16:40.217783+00:00
[2025-03-22T18:16:41.140+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'manual__2025-03-22T18:16:40.217783+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpq4e1wtfw']
[2025-03-22T18:16:41.141+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=403) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-22T18:16:41.141+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask first_task
[2025-03-22T18:16:41.141+0000] {standard_task_runner.py:72} INFO - Started process 404 to run task
[2025-03-22T18:16:41.171+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.first_task manual__2025-03-22T18:16:40.217783+00:00 [running]> on host 4f1e28758fdd
[2025-03-22T18:16:41.211+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T18:16:40.217783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-22T18:16:40.217783+00:00'
[2025-03-22T18:16:41.211+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T18:16:41.235+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-22T18:16:41.236+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello World!']
[2025-03-22T18:16:41.240+0000] {subprocess.py:99} INFO - Output:
[2025-03-22T18:16:41.241+0000] {subprocess.py:106} INFO - Hello World!
[2025-03-22T18:16:41.242+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-22T18:16:41.252+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T18:16:41.253+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=first_task, run_id=manual__2025-03-22T18:16:40.217783+00:00, execution_date=20250322T181640, start_date=20250322T181641, end_date=20250322T181641
[2025-03-22T18:16:41.281+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-22T18:16:41.288+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-22T18:16:41.289+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
