[2025-03-23T22:30:50.645+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T22:30:50.655+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task1 backfill__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-23T22:30:50.660+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task1 backfill__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-23T22:30:50.660+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-23T22:30:50.670+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-03-21 00:00:00+00:00
[2025-03-23T22:30:50.681+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2485) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-23T22:30:50.683+0000] {standard_task_runner.py:72} INFO - Started process 2491 to run task
[2025-03-23T22:30:50.680+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_and_backfill', 'task1', 'backfill__2025-03-21T00:00:00+00:00', '--job-id', '206', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpver_djx2']
[2025-03-23T22:30:50.683+0000] {standard_task_runner.py:105} INFO - Job 206: Subtask task1
[2025-03-23T22:30:50.727+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_and_backfill.task1 backfill__2025-03-21T00:00:00+00:00 [running]> on host 4f1e28758fdd
[2025-03-23T22:30:50.797+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_catchup_and_backfill' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2025-03-21T00:00:00+00:00'
[2025-03-23T22:30:50.798+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-23T22:30:50.804+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-23T22:30:50.805+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Simple bash command']
[2025-03-23T22:30:50.818+0000] {subprocess.py:99} INFO - Output:
[2025-03-23T22:30:50.819+0000] {subprocess.py:106} INFO - Simple bash command
[2025-03-23T22:30:50.820+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-23T22:30:50.840+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-23T22:30:50.842+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill, task_id=task1, run_id=backfill__2025-03-21T00:00:00+00:00, execution_date=20250321T000000, start_date=20250323T223050, end_date=20250323T223050
[2025-03-23T22:30:50.864+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-23T22:30:50.880+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-23T22:30:50.882+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
